### ISSUE TITLE
repetitive variable definitions

### ISSUE THREAD

**Issue by rilexus** [codedgar/Puppertino#2]
There are multiple repetitive variables definitions in the project. I would propose to move them in one place.

**Comment by codedgar** [comment]
Hi! Do you mean in the full.css or in the others?

**Comment by rilexus** [comment]
> Hi! Do you mean in the full.css or in the others?

Yep! Since the master runs with scss now, all the variables can be split up by domain(font, color, padding etc) and moved to one location.
