### ISSUE TITLE
Bug in line 1326 in full.css

### ISSUE THREAD

**Issue by qubit999** [codedgar/Puppertino#26]
There's a bug in line 1326 in full.css.

The line says: 
"bottom: 20%;"

Just comment it out or remove it, it will make the "OK" button too big if it is set. 

full.css code:
>@media (max-width: 568px) {
  .p-modal {
    /* bottom: 20%; user edit from alex */ 
    left: 15%;
    top: unset;
    width: 70vw;
  }

**Comment by codedgar** [comment]
This was addresed in V1.0 in newfull.css, check it out!
