### ISSUE TITLE
ios sizing

### ISSUE THREAD

**Issue by AversaConsulting** [codedgar/Puppertino#31]
Simple issue - the sizing on an ios device seems wrong - for example the mobile bottom nav is huge compared to native... Thanks! Nick

**Comment by codedgar** [comment]
Could you add a screenshot so I can work on it?

**Comment by AversaConsulting** [comment]
![20210413_085304000_iOS](https://user-images.githubusercontent.com/17048490/114526017-83ea2e00-9c3e-11eb-9052-f25f9b04f082.png)
![20210413_085334000_iOS](https://user-images.githubusercontent.com/17048490/114526088-919fb380-9c3e-11eb-8d2a-988153d5c3fb.png)
![20210413_085345000_iOS](https://user-images.githubusercontent.com/17048490/114526122-96fcfe00-9c3e-11eb-854d-5e7b19ce44c4.png)

Hope these help! All on the same device - one from github app and two from puppertino.

Cheers

Nick

**Comment by codedgar** [comment]
Thanks Nick! I've used your screenshots as reference for the improved mobile nav! It should look good now 😎😎

**Comment by AversaConsulting** [comment]
Would you like some more screenshots zipped up on the same size screen from other apps and App Store etc.?

Nick


—————————————-
Nick Denker
Aversa
Office : 01785 330110
Mobile : 07976 256636

________________________________

**Comment by AversaConsulting** [comment]
Would you like some more screenshots of apps and App Store zipped up on the same screen size?

Cheers
Nick
